export const EAppReducers = {
  UPDATE_TALLIES_STATE: 'UPDATE_TALLIES_STATE',
  UPDATE_INVITES_STATE: 'UPDATE_INVITES_STATE',
  UPDATE_PROFILE_STATE: 'UPDATE_PROFILE_STATE',
  UPDATE_LANGUAGE_STATE: 'UPDATE_LANGUAGE_STATE',
  UPDATE_CURRENCY_STATE: 'UPDATE_CURRENCY_STATE',
};
